### ISSUE TITLE
Sound produces Err(Mad(BufLen))

### ISSUE THREAD

**Issue by tomaka** [bendykst/simple-mad.rs#7]
The example sound [here](https://github.com/tomaka/rodio/blob/582a2b80af7363c4606485c41e8775846074e05c/examples/music.mp3) produces `Err(Mad(BufLen))` after a few seconds.

I investigated a bit. When playing the sound [this line](https://github.com/bendykst/simple-mad.rs/blob/49df613de8fbd77e9712252da9d18804e7bff868/simplemad/src/lib.rs#L175) is called twice, and the error happens the second time.

If I change `self.decode_frame()` into `self.get_frame()` it no longer returns an error, but I sometimes get bad sample data when this is called.

Alternatively, increasing [the size of the buffer](https://github.com/bendykst/simple-mad.rs/blob/49df613de8fbd77e9712252da9d18804e7bff868/simplemad/src/lib.rs#L80) to 65536 fixed it totally.

**Comment by tomaka** [comment]
When increasing the size of the buffer, some parts of the sound repeat twice, so it's not a perfect fix.

**Comment by bendykst** [comment]
I created a test for this file, but I could not reproduce the problem. (https://github.com/bendykst/simple-mad.rs/tree/issue-7-testcase)

The file contains 1236 frames with an ID3V1 tag at the end (according to MP3 Diags 1.2.01). When I run the test, 1236 frames are decoded without error. libmad then hits the tag and produces a LostSync error, which simplemad reports. After exhausting the rest of the buffer trying to regain sync, the libmad returns a BufLen error which causes Simplemad to attempt to refill the buffer. When Simplemad reads zero bytes, it suppresses the BufLen error and returns EOF.

**Comment by bendykst** [comment]
I found the source of this issue while trying to use a BufReader. Calls to read on a BufReader sometimes produces a number of bytes smaller than the size of a frame, leaving the Decoder buffer almost empty after a refill attempt. I was unaware that a BufReader would only produce as many bytes as were present in its internal buffer.
