### ISSUE TITLE
The format of the samples should be stronger typed or better documented

### ISSUE THREAD

**Issue by tomaka** [bendykst/simple-mad.rs#8]
Apparently the samples produced by simplemad are in fixed point and need [a conversion step](https://github.com/bendykst/simple-mad.rs/blob/49df613de8fbd77e9712252da9d18804e7bff868/simplemad_sys/libmad-src/minimad.c#L107-L121) before being rendered.

**Comment by bendykst** [comment]
What do you think of this approach? (I'll need to figure out how to do the conversions properly.)
